Feature/lcsk 26 create login page and hook it to strapi
MarioStojcevski/eestec.mk pull request #18
Opened 2023-01-21 15:18 UTC by VasilakiG

Created the look of the login screen, and made it responsive too

2023-01-21 17:22 UTC, MarioStojcevski requested changes

2023-01-21 17:22 UTC, MarioStojcevski commented on frontend/components/login-screen.tsx
> +                    <Box boxShadow='dark-lg' bg='white' border='2px' borderColor='primary' p='6' rounded='lg'>
Please try to use card instead of box here on line 32 and see if it works without adding boxShadow
https://chakra-ui.com/docs/components/card

2023-01-21 17:22 UTC, MarioStojcevski commented on frontend/components/login-screen.tsx
> +                    <Box boxShadow='dark-lg' bg='white' border='2px' borderColor='primary' p='6' rounded='lg'>
Please also, try to make the Card more wide than it is high. I redesigned the login page a little bit.
The card can have e height of 60% view height. `height="60vh"`

ignore the blue outline, it is just selected
<img width="912" alt="image" src="https://user-images.githubusercontent.com/61598148/213878895-062babdb-7f08-45ec-9aac-3d39beb8ee43.png">

2023-01-21 17:22 UTC, MarioStojcevski commented on frontend/components/login-screen.tsx
> +                    <Box boxShadow='dark-lg' bg='white' border='2px' borderColor='primary' p='6' rounded='lg'>
you dont need to add the register button it looks good like this, but make the login button full width, and add the forgot password underneath.

2023-01-21 17:22 UTC, MarioStojcevski commented on frontend/components/login-screen.tsx
> +                        <Image src="/images/eestec-logo.png" maxW='40%' mt='2' mb='10' mx='auto' />
remove the eestec logo, it will be visible from the header.

2023-01-21 17:22 UTC, MarioStojcevski commented on frontend/pages/login.tsx
> +        <LoginScreen />
instead of doing this, move all your code here, and delete the file login-screen.tsx from components

2023-01-22 14:39 UTC, VasilakiG commented on frontend/components/login-screen.tsx
> +                    <Box boxShadow='dark-lg' bg='white' border='2px' borderColor='primary' p='6' rounded='lg'>
Done

2023-01-22 14:39 UTC, VasilakiG commented on frontend/components/login-screen.tsx
> +                        <Image src="/images/eestec-logo.png" maxW='40%' mt='2' mb='10' mx='auto' />
Done

2023-01-22 14:40 UTC, VasilakiG commented on frontend/pages/login.tsx
> +        <LoginScreen />
Done

2023-02-09 18:53 UTC, MarioStojcevski approved these changes

2023-02-09 18:53 UTC, merged